env:
  - GO111MODULE=on

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/saturn-l2

archives:
  - id: macos-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}"
    replacements:
      darwin: macos
      amd64: x86_64

checksum:
  disable: true

signs:
  - signature: "${artifact}_macos.dmg"
    ids:
      - macos-zip
    cmd: gon
    args:
      - .gon.hcl
    artifacts: all

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - 'README'

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/gon_macos.dmg
    - glob: ./dist/gon_macos.zip