# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    id: saturn
    goos:
      - linux
      - windows
    ignore:
    - goos: windows
      goarch: arm64
    main: ./cmd/saturn-l2
    binary: saturn-L2-node
  - env:
      - CGO_ENABLED=0
    id: macos
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/saturn-l2

archives:
  - id: macos-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}"
    replacements:
      darwin: macos
      amd64: x86_64
    builds:
    - macos

checksum:
  disable: true

signs:
  - ids:
      - macos-zip
    cmd: gon
    args:
      - .gon.hcl
    artifacts: all

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - 'README'

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/gon_macos.zip