# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: saturn-L2-node
    id: saturn-L2-node
    goos:
      - linux
      - windows
    ignore:
    - goos: windows
      goarch: arm64
    main: ./cmd/saturn-l2
    env:
      - CGO_ENABLED=0
  - binary: saturn-L2-node
    id: saturn-L2-node-macos
    goos:
    - darwin
    main: ./cmd/saturn-l2
    env:
      - CGO_ENABLED=0
signs:
  - ids:
      - saturn-L2-node-macos
    cmd: gon
    args:
    - .gon.hcl
    artifacts: all

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'

