# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: saturn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    ignore:
    - goos: windows
      goarch: arm64
    main: ./cmd/saturn-l2
    binary: saturn-L2-node
  - id: macos-x86-64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/saturn-l2
  - id: macos-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/saturn-l2

archives:
  - builds:
    - saturn
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  - builds:
    - macos-x86-64
    id: macos-x86-64-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      amd64: x86_64
  - builds:
    - macos-arm64
    id: macos-arm64-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
checksum:
  name_template: 'checksums.txt'
signs:
  - id: macos-x86-64
    ids:
      - macos-x86-64-zip
    cmd: ./sign-arm.sh
    artifacts: all
  - id: macos-arm64
    ids:
      - macos-arm64-zip
    cmd: ./sign-arm.sh
    artifacts: all
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
